# Generated by Django 4.0.1 on 2022-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(db_index=True, max_length=55, unique=True)),
                ('mobile', models.CharField(db_index=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=40, unique=True)),
                ('last_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
